CREATE DATABASE bibliotheque_aout2025;
USE bibliotheque_aout2025;

CREATE TABLE Types(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,label VARCHAR(100) NOT NULL);

CREATE TABLE Books(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,title VARCHAR(255) NOT NULL, release_date DATE NOT NULL, is_available BOOLEAN NOT NULL DEFAUlT true, types_id INT NOT NULL);

CREATE TABLE Users(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, login varchar(255) NOT NULL,password VARCHAR(255) NOT NULL);

CREATE TABLE Loaners(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,lastname VARCHAR(255) NOT NULL,firstname VARCHAR(255) NOT NULL,email VARCHAR(255) NOT NULL,street_number INT NULL,street_name VARCHAR(255) NULL,city VARCHAR(255) NULL,postal_code CHAR(5) NULL,
additional_adress VARCHAR(255) NULL,
user_id INT NULL);

CREATE TABLE Loans(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,loaner_id INT NOT NULL,book_id INT NOT NULL,start_date DATE NOT NULL DEFAULT (CURRENT_DATE),end_date DATE NULL);

CREATE TABLE Authors(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,lastname VARCHAR(255) NOT NULL,firstname VARCHAR(255) NOT NULL,born_at DATE NULL,die_at DATE NULL);

CREATE TABLE Editors(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,label VARCHAR(100) NOT NULL);

CREATE TABLE Genres(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,label VARCHAR(100) NOT NULL);

CREATE TABLE authors_books(book_id INT,author_id INT,PRIMARY KEY(book_id,author_id));

CREATE TABLE editors_books(book_id INT,editor_id INT,PRIMARY KEY(book_id, editor_id));

CREATE TABLE genres_books(book_id INT,genre_id INT,PRIMARY KEY(book_id, genre_id));

ALTER TABLE Loaners ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES Users(id);

ALTER TABLE Loans ADD CONSTRAINT FOREIGN KEY (loaner_id) REFERENCES Loaners(id);

ALTER TABLE Loans ADD CONSTRAINT FOREIGN KEY (book_id) REFERENCES Books(id);

ALTER TABLE Books ADD CONSTRAINT FOREIGN KEY (types_id) REFERENCES Types(id);

ALTER TABLE Authors_Books ADD CONSTRAINT FOREIGN KEY (book_id) REFERENCES Books(id);

ALTER TABLE Authors_Books ADD CONSTRAINT FOREIGN KEY (author_id) REFERENCES Authors(id);

ALTER TABLE Editors_Books ADD CONSTRAINT FOREIGN KEY (editor_id) REFERENCES Editors(id);

 ALTER TABLE Editors_Books ADD CONSTRAINT FOREIGN KEY (book_id) REFERENCES Books(id);

ALTER TABLE Genres_Books ADD CONSTRAINT FOREIGN KEY (book_id) REFERENCES Books(id);

ALTER TABLE Genres_Books ADD CONSTRAINT FOREIGN KEY (genre_id) REFERENCES Genres(id);




